django/mysite/polls/urls.py
from django.urls import path, re_path, include
from . import views

# de serializer
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'questions', views.QuestionViewSet)
# hasta aqui
app_name= 'polls'
urlpatterns = [
    # incluimos api por serializer e importamos el include
    path('api/',include(router.urls)),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalle'),
    path('<int:pk>/vote/', views.vote, name='vote'),
    path('<int:pk>/resultado/', views.ResultsView.as_view(), name='resultado')
]

django/mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django/mysite/polls/views.py
from django.shortcuts import render,  get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question, Choice
# para la funcionde de vote HttpResponseRedirect, Choice, reverse (este hay que poner toda la linea)
from django.urls import reverse
# importamos generic
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')

class CosasDePreguntas(generic.DetailView):
    # esta clase hereda de este y el de Question
    model=Question
    context_object_name = 'encuesta'

""" def detalle(request, id):
    encuesta = get_object_or_404(Question, pk=id)
    return render(
        request,
        'polls/detalle.html',
        {
            'encuesta': encuesta
        }
    )
"""

class DetailView(CosasDePreguntas):
    # model = Question
    template_name = 'polls/detalle.html'

    # def get_query_set(self):
    # cosa = get_object_or_404(Question, pk=id)
    # return render(request, 'polls/resultados.html',{
    #     'encuesta': cosa,
    # }
    # )

"""
def resultado(request, id):
    question = get_object_or_404(Question, pk=id)
    return render(request, 'polls/resultados.html',{
        'encuesta': question,
    }
    )
"""
class ResultsView(CosasDePreguntas):
    model = Question
    template_name = 'polls/resultados.html'

"""def vote(request, id):
    question = get_object_or_404(Question, pk=id)
    try:
        # esto es como el $_POST['choice'] del formulario de input
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        # poner detalle.html
        return render(request, 'polls/detalle.html', {
            'encuesta': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse(f"/polls/{question.id}/resultado/")) 
"""
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        # esto es como el $_POST['choice'] del formulario de input
        selected_choice = question.options.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        # poner detalle.html
        return render(request, 'polls/detalle.html', {
            'encuesta': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:resultado', args=(question.id,)))

# DE SERIALIZER
from rest_framework import viewsets
from .serializer import QuestionSerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all().order_by('pub_date')




"""def index(request): 
    # corta al final en 5 lineas [:5]
    preguntas = Question.objects.order_by('-pub_date')
    return render(
        request, 
        'polls/index.html',
        {
        'latest_question_list':preguntas
        }
    )
"""

django/mysite/polls/templates/polls/detalle.html
<form action="{% url 'polls:vote' encuesta.id %}" method="post">
    <!-- el csrf_token es un token de seguridad para evitar posibles robos de datos -->
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ encuesta.question_text }}</h1>
            <h3>{{encuesta.pub_date}}</h3>
        </legend>
        <!-- errores del formulario -->
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in encuesta.op.all%}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

django/mysite/polls/templates/polls/index.html
<h1>Listado de preguntas </h1>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <!-- para no poner texto directo ponemos el url, ponemos la funcion de url -->
        <li><a href="{% url 'polls:detalle' question.id%}"> {{question.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<!-- paginacion en html -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


<!-- exportar el css -->
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

django/mysite/polls/templates/polls/resultados.html
<h1>{{encuesta.question_text}}</h1>
<h3>{{encuesta.pub_date}}</h3>
<div>
    <ul>
        {% for o in encuesta.options.all %}
            <li>{{ o.choice_text }} {{o.votes}}</li>
        {% endfor %}
    </ul>
</div>

<a href="{% url 'polls:index' %}">Listado</a>
<a href="{% url 'polls:detalle' encuesta.id %}">Vuelta a las encuestas</a>